username = input('Пожалуйста,введите имя пользователя: ')
title =input('Введите заголовок заметки: ')
content =input('Опишите заметку: ')
status =input('Статус вашей заметки: ')
created_date = input('Дата создания заметки в формате "день-месяц-год": ')
issue_date =input('Дата истечения заметки (дедлайн) в формате "день-месяц-год": ')
print(f'Имя пользователя:{username}')
print(f'Заголовок заметки:{title}')
print(f'Описание заметки:{content}')
print(f'Cтатус заметки:{status}')
print(f'Cоздано:{created_date[0:5]}')
print(f'Выполнить до:{issue_date[0:5]}')